package String;

public class string_method {
    public static void main(String[] args) {
        /*
        * .length()
        * .startsWith()
        * .endsWith()
        * .indexOf()
        * .lastIndexOf()
        * .charAt()
        * .compareTo()
        * .compareToIgnoreCase()
        * .equalsIgnoreCase()
        * .equals()
        * .replace()
        * .split()
        * .substring()
        * .toLowerCase()
        * .toUpperCase()
        * .trim()
        * .chars()
        * .codePointAt()
        * .codePointBefore()
        * .codePointCount()
        * .codePoints()
        * .concat()
        * .contains()
        * .contentEquals()
        * .getBytes()
        * .getChars()
        * .hashCode()
        * .intern()
        * .isBlank()
        * .isEmpty()
        * .lines()
        * .matches()
        * .offsetByCodePoints()
        * .regionMatches()
        * .repeat()
        * .replaceAll()
        * .replaceFirst()
        * .strip()
        * .stripLeading()
        * .stripTrailing()
        * .toCharArray()
        * .toString()
        * .subSequence()
        * .getClass()
        * .notify()
        * .notifyAll()
        * .wait()
        * */
        String str=" hello world ";

    }
}
